name: Run Python Script on PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  run-script:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies inline
        run: pip install requests python-dotenv # 👈 Install dependencies needed by process_pr.py

      - name: Run script
        run: python scripts/process_pr.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
